//POSTS CONST
export const POSTS_ERROR = 'POSTS_ERROR';
export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FETCH = 'POSTS_FETCH';
export const POSTDETAIL_ERROR = 'POSTDETAIL_ERROR';
export const POSTDETAIL_LOADING = 'POSTDETAIL_LOADING';
export const POSTDETAIL_FETCH = 'POSTDETAIL_FETCH';
export const CREATE_POSTDETAIL_FETCH = 'CREATE_POSTDETAIL_FETCH';
export const UPDATE_POSTDETAIL_FIELD = 'UPDATE_POSTDETAIL_FIELD';
export const INSERT_POST_LOADING = 'INSERT_POST_LOADING';
export const INSERT_POST_ERRORED = 'INSERT_POST_ERRORED';
export const INSERT_POST = 'INSERT_POST';
export const POST_TO_DELETE = 'POST_TO_DELETE';
export const DELETE_POST_LOADING = 'DELETE_POST_LOADING';
export const DELETE_POST_ERRORED = 'DELETE_POST_ERRORED';
export const DELETE_POST = 'DELETE_POST';
export const UPVOTE = 'UPVOTE';
export const DOWNVOTE = 'DOWNVOTE';

//COMMENT CONTS

export const INSERT_COMMENT_LOADING = 'INSERT_COMMENT_LOADING';
export const INSERT_COMMENT_ERRORED = 'INSERT_COMMENT_ERRORED';
export const INSERT_COMMENT_SUCCESS = 'INSERT_COMMENT_SUCCESS';
export const GET_COMMENT_LOADING = 'GET_COMMENT_LOADING';
export const GET_COMMENT_ERRORED = 'GET_COMMENT_ERRORED';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT_SELECTED = 'DELETE_COMMENT_SELECTED';
export const UPDATE_COMMENT_FIELD = 'UPDATE_COMMENT_FIELD';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_LOADING = 'DELETE_COMMENT_LOADING';
export const DELETE_COMMENT_ERRORED = 'DELETE_COMMENT_ERRORED';
export const UPVOTE_COMMENT = ' UPVOTE_COMMENT';
export const DOWNVOTE_COMMENT = ' DOWNVOTE_COMMENT';

//CATEGORY CONST
export const CATEGORIES_ERROR= 'CATEGORIES_ERROR';
export const CATEGORIES_LOADING= 'CATEGORIES_LOADING';
export const CATEGORIES_FETCH= 'CATEGORIES_FETCH';

export const CATEGORY_DETAIL_ERROR= 'CATEGORY_DETAIL_ERROR';
export const CATEGORY_DETAIL_LOADING= 'CATEGORY_DETAIL_LOADING';
export const CATEGORY_DETAIL_FETCH= 'CATEGORY_DETAIL_FETCH';


